# These are supported funding model platforms

github: LebToki
open_collective: tarek-tarabichi
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
buy_me_a_coffee: LebToki
thanks_dev: # Replace with a single thanks.dev username
